### ISSUE TITLE
Reading data error: list index out of range

### ISSUE THREAD

**Issue by bitpopler** [DYefremov/DemonEditor#180] opened 2023-06-02 20:00 UTC
Hi,

I hav e a VU+ Solo 4K. I also have a Multituner Setup with 8 Unicable (physically its only one) LNBs  for Astra 19.2 and a motorized Dish for playing around, configured as Tuner 9 (or "I"). Everything was working fine until today i probably found a problem. I am actually setting my system up from the start and was scanning and searching different Sat Positions. At the moment I have 16 Satellites in use. When i start Demoneditor now the above error comes up, up until i had only 14 Sats configured everything works fine. I added 2 more today and after setup and scan wanted to backup my settings and the error came up.

![Bildschirmfoto vom 2023-06-02 21-53-52](https://github.com/DYefremov/DemonEditor/assets/135381324/4476c6b7-eb06-4c06-b2d4-37075a07a34d)

**Comment by DYefremov** [comment] 2023-06-02 20:25
Hi,
This is interesting. First of all, if possible, it is desirable that you compress (zip) and send your 'data' folder with all files to the email from my profile. You can just try again to download the files from the Box and send me the last archive from the backup folder.

**Comment by bitpopler** [comment] 2023-06-02 22:12
thank you for your reply. Please find attached the Data Folder. Thanks in
advance.

Am Fr., 2. Juni 2023 um 22:25 Uhr schrieb Dmitriy Yefremov <
***@***.***>:

**Comment by DYefremov** [comment] 2023-06-03 04:19
Hi, 
Unfortunately I don't see attachments.
If you are on Linux, then by default this is the folder:
`~/DemonEditor/data/`

or look at the "Paths" tab in the settings.

**Comment by bitpopler** [comment] 2023-06-03 04:28
Hi,

I do not know where the files went. Maybe a security feature from gmail regarding zip files ? Anyway I attached them here too, hopefully this works. I will try the debug option during the day.

greets
[data.zip](https://github.com/DYefremov/DemonEditor/files/11641709/data.zip)

**Comment by bitpopler** [comment] 2023-06-03 04:40
Good Morning,

I attached the files on github thread, hope this works.

greets

Am Sa., 3. Juni 2023 um 06:19 Uhr schrieb Dmitriy Yefremov <
***@***.***>:

**Comment by DYefremov** [comment] 2023-06-03 09:04
Ok, thx.
I see where the problem is. The main question is a problem in the app itself or a problem on the  the Box side (may lamedb file formed incorrectly).

**Comment by bitpopler** [comment] 2023-06-03 09:14
Hi,

it is totally possible that the fault is on the box side because I use a
very rare configuration (3 physical Tuners, 1 and 2 connected to Unicable
19.2 Astra for a total of 8 virtual tuners and 1 extra bought tuner for a
rotary dish pointing from 52 East to 30 West with at least 20 Sats when I
am finished scanning using DiseqC 1.2). It is totally normal for me to have
12000+ Channels, maybe that is too much. But I also remembered one thing
when the problem started to occur (it was working perfectly before), on One
Sat Position I did a blindscan with the blindscan plugin provided with the
image becauseI was not sure if the rotor pointed correctly (VTI 15.02 is
the Image in use), maybe this plugin broke the lamedb ?

greets

Am Sa., 3. Juni 2023 um 11:04 Uhr schrieb Dmitriy Yefremov <
***@***.***>:

**Comment by DYefremov** [comment] 2023-06-03 09:18
> maybe this plugin broke the lamedb

Very similar. At least,  I see strange spaces in the file.

```
27ce:00300000:00c9:0055:25:0
Viasat History HD

p:TV3 Group
74ce:00c00000:03f8:0001:25:0
DAZN LaLiga2 HD
p:
d1ce:011a0000:0841:0002:25:0
NBCNewsNowHD
```

**Comment by DYefremov** [comment] 2023-06-03 11:09
Yes, this is a bug in the lamedb file itself. I checked it in other editors (e.g. dreamboxEDIT also "swears" at this file and skips a couple of services). Added a fix for this case. Services are not skipped and remain in the list, but are slightly corrected (in our case, it remove an extra line break).

**Comment by bitpopler** [comment] 2023-06-03 11:37
Hi,

great news checking for updates, thank you very much (I waited so long for
a linux editor, I am so happy that I do not need a vm anymore)

greets

Am Sa., 3. Juni 2023 um 13:09 Uhr schrieb Dmitriy Yefremov <
***@***.***>:

**Comment by bitpopler** [comment] 2023-06-03 11:52
Hi,

I tested with the development branch and can confirm all is working fine now, Thank you.

greets

**Comment by DYefremov** [comment] 2023-06-03 12:11
Great! We can close.

**Closed by DYefremov** 2023-06-03 12:11 UTC
